### ISSUE TITLE
Set up project modules

### ISSUE THREAD

**Issue by whiskeysierra** [whiskeysierra/tracer#1]
- `trace-core`
- `trace-slf4j`
- `trace-spring` (maybe this can be done in a more generic way?)
- `trace-servlet`
- `trace-cxf` (maybe this can be done in a more generic way?)
- `trace-httpcomponents` (as an alternative to spring + cxf)

**Comment by adriancole** [comment]
I don't have a way to contact you so sorry about this :) I think it would be cool to add tracer to the agenda of our pow-wow in Berlin next month https://docs.google.com/document/d/16qNbn6IU43FuNMIie0rgWswIjWUCZUU0yNHxeR1vlRk/edit
(agenda)

https://docs.google.com/document/d/1pQTpGRo1caOJgjeX2Gybx0-_OeTLg3s1V-DrasBX_NQ/edit
(details we'd love to hear about your tracing system)

https://drive.google.com/drive/folders/0B0tSnQT3uGdAflJLdEFhVzl6dEtrN0tPOFhmclFpOFJ5a01nZnFZaXdxdUJ2TUJfOGxhWUE
(shared folder with other implementors of tracing)

It is usually the case that someone drops out or doesn't attend the second day, so if you are free let's try to get you there. looks like impressive work.

**Comment by whiskeysierra** [comment]
@adriancole I definitely won't make it on Feb 20-21. Both dates are pretty much cramped with personal stuff already. I added some content to the Zalando document. Take a look and let me know if you're missing something. I put @LappleApple in the loop. She is our Open Source Evangelist.

**Comment by adriancole** [comment]
thanks very much!
